version: "3.7"

services:
 
    oracle:
        image: hieukhac178/oracledb:1.0
        container_name: oracle
        ports:
            - "1521:1521"
    zoo1:
        image: confluentinc/cp-zookeeper:6.1.1
        hostname: zoo1
        container_name: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        # volumes:
            # - ./zk-single-kafka-single/zoo1/data:/data
            # - ./zk-single-kafka-single/zoo1/datalog:/datalog



    broker1:
        image: confluentinc/cp-kafka:6.1.1
        hostname: broker1
        user: root
        container_name: broker1
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: 'zoo1:2181'
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        # volumes:
            # - ./zk-single-kafka-single/broker1/data:/var/lib/kafka/data
        depends_on:
            - zoo1



    kowl:
        image: quay.io/cloudhut/kowl:v1.5.0
        restart: on-failure
        container_name: kowl
        hostname: kowl
        environment:
            KAFKA_BROKERS: 'broker1:29092'
        ports:
            - "8080:8080"
        depends_on:
            - broker1

    account:
        image: account:1.0
        container_name: account
        ports:
            - "5000:80"
        volumes:
            - ./config/account/appsettings.json:/app/appsettings.json
        depends_on:
            - oracle
            - zoo1
            - kowl
            - broker1
    order:
        image: order:1.0
        container_name: order
        volumes:
            - ./config/order/appsettings.json:/app/appsettings.json
        depends_on:
            - oracle
            - zoo1
            - kowl
            - broker1
            - account
    